### ISSUE TITLE
Stop working after HASS restart

### ISSUE THREAD

**Issue by ennilein** [croedel/MTECmqtt#1]
Hey Christian :) first - a really big THANK YOU for your work! I had already given up hope of ever being able to display the data from my M-TEC in Home Assistant.

One problem, i have installed a Ubuntu VM on my Synology and cofigure the MQTT. All is working fine and i can see all datas via Mosquitto in HASS. But when i have to restart my Home Assistant i don't see any datas...

I get the following:

![image](https://github.com/croedel/MTECmqtt/assets/63798578/aec6b5bc-941a-49fc-8efd-52796704cfa9)
![image](https://github.com/croedel/MTECmqtt/assets/63798578/25b5eb20-85a4-48a2-bc76-f81f9fdaae94)

Can you help maybe? Thank you

**Comment by croedel** [comment]
Hi, thanks for raising the issue and the good description!
I was able to reproduce the issue and will have a look on it

**Comment by croedel** [comment]
I think I foud the issue: My service re-sends the discovery info instantly after it receive the HASS birth message. It seems that HASS unfortunately is not able to handle the discovery info at that time reliably. :-( 
I now added a few seconds sleep to give HASS some grace time.  (Can be configured via HASS_BIRTH_GRACETIME in config.yaml). This seems to do the job.

**Comment by ennilein** [comment]
Wow. Mega. That will help a lot. In the meantime I do it like this: I end the script before rebooting the Home assistant, make all updates and than start the script again. With the change, I have to watch out less. Thank you very much. I would be happy to send a donation if you tell me where.

PS: I reworked the picture a bit :)

![image](https://github.com/croedel/MTECmqtt/assets/63798578/63b7bf90-f92d-42bb-bdb8-326850a11f13)

**Comment by croedel** [comment]
Nice re-worked picture! I would appreciate to include it as alternative backgound image, if you would be OK with that (and send me the .png)

**Comment by ennilein** [comment]
Hello, I completely forgot to get back to you. Your fix worked. Everything works fine again after restarting Home Assistant. Thank you very much for the quick help.
