### ISSUE TITLE
Connection refused since Software Update to V1.0.0.1-V28.53.5.0

### ISSUE THREAD

**Issue by danunt97** [croedel/MTECmqtt#2]
Thank you for this great tool. It worked perfectly for the past six months. However, after a software update on my Energy Butler 12kW-3P-3G40 to version V1.0.0.1-V28.53.5.0, my setup stopped working. Unfortunately, I don't have information about the previous version as I never documented it.

[ERROR] Connection to (192.168.178.69, 5743) failed: [Errno 61] Connection refused

**Comment by tactic123** [comment]
First of all thanks for the great tool!
I do have the same issue too, after the update its no longer working.
I tried everything I can but seems the port is different now.
doing a nmap it seems only TCP 502 is still up on the box.

Any Idea what's going on?

**Comment by croedel** [comment]
It seems that M-TEC changed the modbus port with probably Firmware V27.52.4.0.
The new port is indeed TCP 502.
To adapt on that, you need to change MODBUS_PORT in config.yaml to 502.
This should do the trick. It would be great if you could give me feedback if it works for you! :-)

**Comment by tactic123** [comment]
Thanks, that did the trick.
Could have thought to change the port In the config myself:)

**Comment by croedel** [comment]
Happy that it worked

**Comment by croedel** [comment]
done
